/* Generated by re2c 2.0.3 on Tue Dec 15 00:10:54 2020 */
#line 1 "main.re"
// re2c $INPUT -o $OUTPUT -i
#include <assert.h>                 //
#include <stdio.h>
#include <inttypes.h>
#include <stdlib.h>
#include <string.h>

int16_t stack[100] = { 0 };
uint8_t sn = 0;

void push(int16_t v) { stack[sn++] = v; }
int16_t pop(void) { if (sn == 0) { return -1; } return stack[sn--]; }
                                    // C/C++ code
int lex(const char *YYCURSOR)       //
{
    char *t = YYCURSOR;
    
#line 21 "main.c"
{
	char yych;
	yych = *YYCURSOR;
	switch (yych) {
	case '*': goto yy3;
	case '+': goto yy5;
	case '-': goto yy7;
	case '.': goto yy9;
	case '/': goto yy11;
	case '0' ... '9': goto yy13;
	default: goto yy2;
	}
yy2:
yy3:
	++YYCURSOR;
#line 27 "main.re"
	{ int16_t a = pop(); int16_t b = pop(); push(a+b); }
#line 39 "main.c"
yy5:
	++YYCURSOR;
#line 24 "main.re"
	{ int16_t a = pop(); int16_t b = pop(); push(a+b); }
#line 44 "main.c"
yy7:
	++YYCURSOR;
#line 25 "main.re"
	{ int16_t a = pop(); int16_t b = pop(); push(a+b); }
#line 49 "main.c"
yy9:
	++YYCURSOR;
#line 29 "main.re"
	{ printf(" = %d ", pop()); }
#line 54 "main.c"
yy11:
	++YYCURSOR;
#line 26 "main.re"
	{ int16_t a = pop(); int16_t b = pop(); push(a+b); }
#line 59 "main.c"
yy13:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0' ... '9': goto yy13;
	default: goto yy15;
	}
yy15:
#line 28 "main.re"
	{ printf(">'%s'< %d\n", t, atoi(t)); push(atoi(t)); }
#line 69 "main.c"
}
#line 30 "main.re"

}                                   //

void parse(const char *s) {
    char c[32] = { 0 };
    strcpy(c, s);
    char *token = strtok(c, " ");
    while (token) {
        lex(token);
        token = strtok(NULL, " ");
    }
}
                                    //
int main()                          //
{                                   // C/C++ code
    parse("1 2 12 + + .");
    printf("%d\n", lex("_Zer0"));
    return 0;                       //
}                                   //
